/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import javax.swing.JTable;
import javax.swing.JTextField;

import Controller.ApotekController;
import javax.swing.JTable;

/**
 *
 * @author ACER
 */
public class MainView extends javax.swing.JFrame {
    ApotekController ac;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        ac = new ApotekController(this);    
        ac.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelMainView = new javax.swing.JPanel();
        jPanelGambar = new javax.swing.JPanel();
        jLabelGambar = new javax.swing.JLabel();
        jPanelUtama = new javax.swing.JPanel();
        jLabelJudul = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TFID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFKadaluarsa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonTambah = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        TFHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clr = new javax.swing.JButton();
        TFCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonDataAwal = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelola Stok");

        jPanelMainView.setBackground(new java.awt.Color(64, 89, 143));

        jPanelGambar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apotek.png"))); // NOI18N

        javax.swing.GroupLayout jPanelGambarLayout = new javax.swing.GroupLayout(jPanelGambar);
        jPanelGambar.setLayout(jPanelGambarLayout);
        jPanelGambarLayout.setHorizontalGroup(
            jPanelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGambarLayout.setVerticalGroup(
            jPanelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelUtama.setBackground(new java.awt.Color(102, 255, 255));

        jLabelJudul.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabelJudul.setForeground(new java.awt.Color(64, 89, 143));
        jLabelJudul.setText("Program Kelola Stok ");

        showTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showTable.setForeground(new java.awt.Color(64, 89, 143));
        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title5"
            }
        ));
        showTable.setGridColor(new java.awt.Color(64, 89, 143));
        showTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(showTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 89, 143));
        jLabel1.setText("ID Obat");

        TFID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TFID.setForeground(new java.awt.Color(64, 89, 143));
        TFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 89, 143));
        jLabel2.setText("Nama");

        TFNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TFNama.setForeground(new java.awt.Color(64, 89, 143));
        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });

        TFStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TFStock.setForeground(new java.awt.Color(64, 89, 143));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 89, 143));
        jLabel3.setText("Harga");

        TFKadaluarsa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TFKadaluarsa.setForeground(new java.awt.Color(64, 89, 143));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 89, 143));
        jLabel4.setText("Kadaluarsa");

        jButtonTambah.setBackground(new java.awt.Color(64, 89, 143));
        jButtonTambah.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTambah.setText("Tambah");
        jButtonTambah.setToolTipText("");
        jButtonTambah.setBorderPainted(false);
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonUbah.setBackground(new java.awt.Color(64, 89, 143));
        jButtonUbah.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonUbah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUbah.setText("Ubah");
        jButtonUbah.setToolTipText("");
        jButtonUbah.setBorderPainted(false);
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(64, 89, 143));
        jButtonHapus.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHapus.setText("Hapus");
        jButtonHapus.setToolTipText("");
        jButtonHapus.setBorderPainted(false);
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(64, 89, 143));
        jButtonClear.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");
        jButtonClear.setToolTipText("");
        jButtonClear.setBorderPainted(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(64, 89, 143));
        jButtonLogout.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.setToolTipText("");
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        TFHarga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TFHarga.setForeground(new java.awt.Color(64, 89, 143));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 89, 143));
        jLabel5.setText("Stok");

        clr.setBackground(new java.awt.Color(64, 89, 143));
        clr.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        clr.setForeground(new java.awt.Color(255, 255, 255));
        clr.setText("Clear Input");
        clr.setToolTipText("");
        clr.setBorderPainted(false);
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        TFCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCariActionPerformed(evt);
            }
        });

        jButtonCari.setBackground(new java.awt.Color(64, 89, 143));
        jButtonCari.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonCari.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCari.setText("Cari");
        jButtonCari.setToolTipText("");
        jButtonCari.setBorderPainted(false);
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jButtonDataAwal.setBackground(new java.awt.Color(64, 89, 143));
        jButtonDataAwal.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButtonDataAwal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDataAwal.setText("Data Awal");
        jButtonDataAwal.setToolTipText("");
        jButtonDataAwal.setBorderPainted(false);
        jButtonDataAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataAwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUtamaLayout = new javax.swing.GroupLayout(jPanelUtama);
        jPanelUtama.setLayout(jPanelUtamaLayout);
        jPanelUtamaLayout.setHorizontalGroup(
            jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUtamaLayout.createSequentialGroup()
                        .addComponent(TFCari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDataAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabelJudul)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelUtamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelUtamaLayout.createSequentialGroup()
                                            .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(29, 29, 29)
                                            .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(TFID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TFNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TFStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TFHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFKadaluarsa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelUtamaLayout.createSequentialGroup()
                                .addComponent(jButtonLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clr)))
                        .addContainerGap())))
        );
        jPanelUtamaLayout.setVerticalGroup(
            jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonDataAwal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(TFKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTambah)
                            .addComponent(jButtonUbah))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHapus)
                            .addComponent(jButtonClear))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLogout)
                            .addComponent(clr))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainViewLayout = new javax.swing.GroupLayout(jPanelMainView);
        jPanelMainView.setLayout(jPanelMainViewLayout);
        jPanelMainViewLayout.setHorizontalGroup(
            jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMainViewLayout.setVerticalGroup(
            jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMainView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMainView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        ConfirmView cv = new ConfirmView("Logout", this, null);
        cv.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        ConfirmView cv = new ConfirmView("hapus data?", null, ac);
        cv.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        ConfirmView cv = new ConfirmView("ubah data?", null, ac);
        cv.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        ConfirmView cv = new ConfirmView("membersihkan data?", null, ac);
        cv.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void TFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIDActionPerformed

    private void showTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTableMouseClicked
        int baris = showTable.getSelectedRow();
        TFID.setText(showTable.getValueAt(baris, 0).toString());
        TFNama.setText(showTable.getValueAt(baris, 1).toString());
        TFStock.setText(showTable.getValueAt(baris, 3).toString());
        TFHarga.setText(showTable.getValueAt(baris, 2).toString());
        TFKadaluarsa.setText(showTable.getValueAt(baris, 4).toString());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_showTableMouseClicked

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        TFID.setText("");
        TFNama.setText("");
        TFStock.setText("");
        TFHarga.setText("");
        TFKadaluarsa.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_clrActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        if (TFID.getText().equals("") || TFNama.getText().equals("") || TFStock.getText().equals("") || TFHarga.getText().equals("") || TFKadaluarsa.getText().equals("")) {
            ErrorView cv = new ErrorView("Data tidak boleh kosong");
            cv.setVisible(true);
        } else if (!TFStock.getText().matches("[0-9]+") || !TFHarga.getText().matches("[0-9]+")) {
            ErrorView cv = new ErrorView("Stock dan Harga harus angka");
            cv.setVisible(true);
        } else if (TFStock.getText().length() > 5 || TFHarga.getText().length() > 10) {
            ErrorView cv = new ErrorView("Stock maksimal 5 digit, Harga maksimal 10 digit");
            cv.setVisible(true);
        } else {
            ac.insert();
            ac.isiTable();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        ac.cari();
        String cari = TFCari.getText();
        ac.cariTable(cari);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void TFCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCariActionPerformed

    private void jButtonDataAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataAwalActionPerformed
        ac.isiTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDataAwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFCari;
    private javax.swing.JTextField TFHarga;
    private javax.swing.JTextField TFID;
    private javax.swing.JTextField TFKadaluarsa;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFStock;
    private javax.swing.JButton clr;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDataAwal;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JPanel jPanelGambar;
    private javax.swing.JPanel jPanelMainView;
    private javax.swing.JPanel jPanelUtama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable showTable;
    // End of variables declaration//GEN-END:variables

    public JTextField getTFHarga() {
        return TFHarga;
    }

    public void setTFHarga(JTextField TFHarga) {
        this.TFHarga = TFHarga;
    }

    public JTextField getTFID() {
        return TFID;
    }

    public void setTFID(JTextField TFID) {
        this.TFID = TFID;
    }

    public JTextField getTFKadaluarsa() {
        return TFKadaluarsa;
    }

    public void setTFKadaluarsa(JTextField TFKadaluarsa) {
        this.TFKadaluarsa = TFKadaluarsa;
    }

    public JTextField getTFNama() {
        return TFNama;
    }

    public void setTFNama(JTextField TFNama) {
        this.TFNama = TFNama;
    }

    public JTextField getTFStock() {
        return TFStock;
    }

    public void setTFStock(JTextField TFStock) {
        this.TFStock = TFStock;
    }

    public JTable getShowTable() {
        return showTable;
    }

    public void setShowTable(JTable showTable) {
        this.showTable = showTable;
    }

    public JTextField getTFCari() {
        return TFCari;
    }

    public void setTFCari(JTextField TFCari) {
        this.TFCari = TFCari;
    }
}
